Repository DevCom-Kanyakumari/flutter-starter-app, pull requests merged in 2022-10, with the labels that each got.

#1 Update README.md
  README.md
Labels: help wanted, hacktoberfest, hacktoberfest2022

#4 theme changes
  lib/main.dart
Labels: good first issue, hacktoberfest, hacktoberfest2022

#5 login and signup created
  lib/main.dart
  lib/pages/Login.dart
  lib/pages/signup.dart
Labels: help wanted, hacktoberfest, hacktoberfest2022

#6 By RK
  README.md
  lib/main.dart
  lib/pages/Login.dart
Labels: hacktoberfest, hacktoberfest2022

#7 updated the main screen UI
  img/Screenshot from 2022-10-12 23-12-59.png
  lib/main.dart
Labels: hacktoberfest, hacktoberfest2022

#9 README and Lib
  README.md
  lib/pages/signup.dart
Labels: hacktoberfest, hacktoberfest2022

#10 Contributor Profile
  lib/main.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: hacktoberfest, hacktoberfest2022

#12 added login & sign in
  .fvm/flutter_sdk
  .fvm/fvm_config.json
  android/app/build.gradle
  android/app/src/main/java/io/flutter/app/FlutterMultiDexApplication.java
  ios/Runner/GoogleService-Info.plist
  ios/firebase_app_id_file.json
  lib/main.dart
  lib/models/User_model.dart
  lib/pages/Login.dart
  lib/pages/home_page.dart
  lib/pages/signup.dart
  macos/Runner/GoogleService-Info.plist
  macos/firebase_app_id_file.json
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: hacktoberfest, hacktoberfest2022

#16 Account Page
  lib/pages/Login.dart
  lib/pages/account.dart
Labels: hacktoberfest, hacktoberfest2022

#17 loginscreen ui updated
  lib/pages/Login.dart
Labels: hacktoberfest, hacktoberfest2022

#18 updated the login and signup design
  img/hello.gif
  lib/pages/Login.dart
  lib/pages/home_page.dart
  lib/pages/signup.dart
  pubspec.yaml
Labels: hacktoberfest, hacktoberfest2022
